env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
  parser: '@typescript-eslint/parser'
  project:
    - ./tsconfig.json
    - ./tsconfig.node.json
rules:
  '@typescript-eslint/strict-boolean-expressions': off
  '@typescript-eslint/comma-dangle': off
  '@typescript-eslint/space-before-function-paren': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-unsafe-argument': off
  '@typescript-eslint/prefer-nullish-coalescing': off
